name: vibe-translator
region: nyc

functions:
  - name: generate
    source_dir: api
    environment_slug: node-js
    envs:
      - key: REPLICATE_API_TOKEN
        scope: RUN_TIME
        type: SECRET

static_sites:
  - name: vibe-translator-web
    github:
      branch: main
      deploy_on_push: true
    build_command: npm run build
    output_dir: dist
    catchall_document: index.html
    routes:
      - path: /
    environment_slug: node-js
    envs: []
